productName: "HTTPBin-Headers"
productDescription: "This is a simple HTTPBin API based on the OpenAPI 3.0 specification."
productPublish: true
productVersionStatus: "published"
productDeprecated: false
portalId: "17ae2de0-cd7e-4d30-97b4-8aee8d14efce"
deleted: false
sharedFlowAuth: false
sharedFlowObservability: false
