productName: "HTTPBin-Headers"
productDescription: "This is a simple HTTPBin API based on the OpenAPI 3.0 specification."
productPublish: true
productVersionStatus: "published"
productDeprecated: false
portalId: "d3a1b06e-b09a-4eb9-bc9c-c18fd1b9a2bc"
deleted: false
sharedFlowAuth: false
sharedFlowObservability: false
