productName: "HTTPBin-Headers"
productDescription: "This is a simple HTTPBin API based on the OpenAPI 3.0 specification."
productPublish: true
productVersionStatus: "published"
productDeprecated: false
portalId: "fc75aef8-7580-408e-b448-cbcca4c966cd"
deleted: false
sharedFlowAuth: false
sharedFlowObservability: false
