productName: "HTTPBin-Headers"
productDescription: "This is a simple HTTPBin API based on the OpenAPI 3.0 specification."
productPublish: true
productVersionStatus: "published"
productDeprecated: false
portalId: "30120ef1-fc77-4965-98b4-ed02f4a6626b"
deleted: false
sharedFlowAuth: false
sharedFlowObservability: false
