productName: "HTTPBin-Headers"
productDescription: "This is a simple HTTPBin API based on the OpenAPI 3.0 specification."
productPublish: true
productVersionStatus: "published"
productDeprecated: false
portalId: "53b0818f-a939-482d-9fab-d5864fb0de81"
deleted: false
sharedFlowAuth: false
sharedFlowObservability: false
