productName: "HTTPBin-Headers"
productDescription: "This is a simple HTTPBin API based on the OpenAPI 3.0 specification."
productPublish: true
productVersionStatus: "published"
productDeprecated: false
portalId: "5833a81d-9b95-4115-9e29-544fee3c989b"
deleted: false
sharedFlowAuth: false
sharedFlowObservability: false
