productName: "HTTPBin-Headers"
productDescription: "This is a simple HTTPBin API based on the OpenAPI 3.0 specification."
productPublish: true
productVersionStatus: "published"
productDeprecated: false
portalId: "5983ed9f-784b-4c78-ac49-8b3092f0e195"
deleted: false
sharedFlowAuth: false
sharedFlowObservability: false
